
project_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" 

[api]
# Port to use for the API URL.
port = 54321
# Enable JWT verification for API requests
enabled = true

[db]
# Port to use for the local database URL.
port = 54322

[studio]
# Port to use for Supabase Studio.
port = 54323

# Email testing server. Emails sent with the local dev setup are not actually delivered, rather they
# are captured and can be viewed from the configured port.
[inbucket]
# Port to use for the email testing server web interface.
port = 54324

[storage]
# Port to use for the storage server.
port = 54325

[auth]
# Port to use for the auth server.
port = 54326

[edge_functions]
# Port to use for the Edge Functions server.
port = 54327

[functions.create-payment]
verify_jwt = false
