
project_id = "yfrknhddxvixxqfgggdy"

[auth.smtp]
host = "smtp-relay.sendinblue.com"
port = 587
user = "your_brevo_smtp_username"
pass = "your_brevo_smtp_password"
sender_name = "Catatuy"
sender_email = "no-reply@catatyo.com"
admin_email = "admin@catatyo.com"
