
project_id = "yfrknhddxvixxqfgggdy"

[auth.smtp]
host = "smtp-relay.sendinblue.com"
port = 587
user = "your_brevo_smtp_username"
pass = "your_brevo_smtp_password"
sender_name = "Catatuy"
sender_email = "no-reply@catatyo.com"
admin_email = "admin@catatyo.com"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.email.template.recovery]
subject = "Reset Your Password - Catatuy"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.invite]
subject = "You have been invited - Catatuy"
content_path = "./supabase/templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirm Your Email - Catatuy"
content_path = "./supabase/templates/confirmation.html"
